### PR TITLE
Fishing module

### PR DESCRIPTION
**Pull request by IsaacLaquerre**
there I left a description so github won't be triggered

### CODE REVIEW

**Comment by Dmunch04** [comment]
Seems like some of the code is wrongly indented and you should use the helper method for sending message to player instead of doing `p.sendMessage(ChatColor.translateAlternateColorCodes(..));`

**Comment by IsaacLaquerre** [comment]
> Seems like some of the code is wrongly indented and you should use the helper method for sending message to player instead of doing `p.sendMessage(ChatColor.translateAlternateColorCodes(..));`

fixed

**Comment by Dmunch04** [comment]
The last part as well?

**Comment by IsaacLaquerre** [comment]
as in?

**Comment by Dmunch04** [comment]
Your way of sending messages to the player

**Comment by IsaacLaquerre** [comment]
well yeah check the commit

**Comment by Dmunch04** [comment]
Okay my bad. Merging then

**Pull request merged**
